name: Build and Push to ECR

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    name: Build and Push Docker Image to Docker Hub
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout the repository'
        uses: actions/checkout@v3

      - name: 'login to dockerhub'
        env:
          USERNAME: ${{secrets.DOCKER_HUB_USER}}
          PASSWORD: ${{secrets.DOCKER_HUB_PASS}}
        run: docker login --username $USERNAME --password $PASSWORD

      - name: 'deploy to dockerhub'
        run: |
          TIMESTAMP=$(date +'%y%m%d%H%M%S')
          docker image build -t klynton2000/my_app_be:$TIMESTAMP -t klynton2000/my_app_be:latest .
          docker image push klynton2000/my_app_be:$TIMESTAMP
          docker image push klynton2000/my_app_be:latest

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop my_app_be || true && docker rm my_app_be || true && docker rmi $(docker images --filter="reference=klynton2000/my_app_be" --quiet) || true && docker run -d --name my_app_be -p 3030:3030 -v ~/my_app_be/public:/app/public --restart=unless-stopped --env-file ~/my_app-be_env/.env klynton2000/my_app_be:latest